import Config

# Configure your database
config :fleet_mint, FleetMint.Repo,
  username: "think",
  password: "password1",
  hostname: "localhost",
  database: "fleet_mint_dev",
  port: 5433,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fleet_mint, FleetMintWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4004],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "KM9YEKdDVU6U06qglipUWJ0nxM2lFfje7UV+6TYJFD5bvjXK7+lcc9dNOoBjF5aT",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:fleet_mint, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:fleet_mint, ~w(--watch)]}
  ]

# Guardian secret_key for dev only — never reused in prod.
config :fleet_mint, FleetMint.Identity.Guardian,
  secret_key: "Pok4A6jLxG+B+BrFh4kFrSccAQZXOKlaAgCILyoFYhW/4uW2dVJMpous0fsKHwzj"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :fleet_mint, FleetMintWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/fleet_mint_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :fleet_mint, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# QR ticket signing secret (dev only — use a strong random value in production).
config :fleet_mint, :qr_secret, "dev_only_qr_secret_change_in_prod"

# VAT rate applied to freight invoices (Zambia standard rate). Override in production
# or runtime.exs if the rate changes — no redeployment required.
config :fleet_mint, :vat_rate, "0.16"
